# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  be:
    build:
      context: callisto
    secrets:
      - google_credentials
      - gcs_credentials
    command: --secret /run/secrets/google_credentials --gcs-bucket callisto-be-user-profiles --web-server http://localhost:50001
    environment:
      RUST_LOG: debug
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcs_credentials
    expose:
      - 30000
    ports:
      - 30000:30000
  fe:
    build:
      context: fe/callisto
    environment:
      NODE_ENV: production
      REACT_APP_C_BACKEND: localhost:30000
    expose:
      - 3000
    ports:
      - 50001:3000
secrets:
  google_credentials:
    file: callisto/secrets/google_credentials.json
  gcs_credentials:
    file: ~/.config/gcloud/application_default_credentials.json


