[package]
name = "tracing-gcp"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
google_cloud_logging = "0.1.0"
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
