name: Canary Env -- Build Canary Callisto Rust backend and run on Cloud Run

on:
  push:
    branches:
      - canary
      - dev-tutorial-deploy
    paths:
      - 'callisto/**'
      - '.github/workflows/canary-be-merge.yml'
  workflow_dispatch:  

env:
  PROJECT_ID: callisto-canary
  GAR_LOCATION: gcr.io
  REGION: us-central1
  APP: callisto-be
  GENERAL_ARGS: --secret,/secrets/google_credentials,--users_file,gs://callisto-be-user-profiles/authorized_users,--design_file,gs://callisto-scenarios/default_ship_templates.json
  APP_ARGS: --web-server,https://canary.callistoflight.com,--scenario_file,gs://callisto-scenarios/sol.json
  TUTORIAL_ARGS: --web-server,https://tutorial.canary.callistoflight.com,--scenario_file,gs://callisto-scenarios/tutorial.json
  TUTORIAL_APP: callisto-be-tutorial
  PORT: 30000

jobs:
  deploy-canary:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout for Canary'
        uses: 'actions/checkout@v4'

      - name: 'Google auth with Canary Creds'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WIF_CANARY_PROVIDER }}' 
          service_account: '${{ secrets.WIF_CANARY_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 501.0.0'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}

      - name: Set up Docker buildx for Canary
        uses: docker/setup-buildx-action@v3

      - name: Build and push container with Docker GHA
        uses: 'docker/build-push-action@v4'
        with:
          context: ./callisto
          push: true
          tags: ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.APP }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Deploy to Canary Cloud Run'
        run:
          gcloud run deploy ${{ env.APP }} --port=${{ env.PORT }} --image ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.APP }}:${{ github.sha }}  --region=${{ env.REGION }} 
            --update-secrets=/secrets/google_credentials=google_credentials:latest --args=${{ env.APP_ARGS }},${{ env.GENERAL_ARGS }}
      - name: 'Deploy tutorial to Canary Cloud Run'
        run:
          gcloud run deploy ${{ env.TUTORIAL_APP }} --port=${{ env.PORT }} --image ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/${{ env.APP }}:${{ github.sha }}  
            --region=${{ env.REGION }} --update-secrets=/secrets/google_credentials=google_credentials:latest --args=${{ env.TUTORIAL_ARGS }},${{ env.GENERAL_ARGS }}